const { XyoWinstonLogger, XyoBase } = require("./dist")
const log = new XyoWinstonLogger()
const test = new XyoBase()
test.logInfo("test")
log.logInfo("test 3")
log.logVerbose("test 4")
log.logWarning("test 5")
log.logDebug("test 1")
log.logDebug("test 1")
log.logError("test 2")
log.logInfo("test 3")
log.logInfo("test 3")
log.logVerbose("test 4")
log.logWarning("test 5")
log.logDebug("test 1")
log.logError("test 2")
log.logVerbose("test 4")
log.logWarning("test 5")
log.logDebug("test 1")
log.logError("test 2")
log.logInfo("test 3")
log.logVerbose("test 4")
log.logWarning("test 5")
log.logDebug("test 1")
log.logError("test 2")
log.logInfo("test 3")
log.logVerbose("test 4")
log.logWarning("test 5")
log.logError("test 2")

